background_opacity: 0.85
colors:
  bright:
    black:   '#000507'
    blue:    '#023550'
    cyan:    '#02899e'
    green:   '#93d0cb'
    magenta: '#023550'
    red:     '#d9483b'
    white:   '#a0cecb'
    yellow:  '#f2c12e'
  dim:
    black:   '#000507'
    blue:    '#023550'
    cyan:    '#02899e'
    green:   '#93d0cb'
    magenta: '#023550'
    red:     '#d9483b'
    white:   '#a0cecb'
    yellow:  '#f2c12e'
  normal:
    black:   '#000507'
    blue:    '#023550'
    cyan:    '#02899e'
    green:   '#93d0cb'
    magenta: '#023550'
    red:     '#d9483b'
    white:   '#a0cecb'
    yellow:  '#f2c12e'
  primary:
     background: '#000507'
     foreground: '#a0cecb'
font:
  bold:
    family: Inconsolata for Powerline
    style: Regular
  normal:
    family: Inconsolata for Powerline
  size: 10
key_bindings:
  - { key: Key0, mods: Alt, chars: "\x1b0" }
  - { key: Key1, mods: Alt, chars: "\x1b1" }
  - { key: Key2, mods: Alt, chars: "\x1b2" }
  - { key: Key3, mods: Alt, chars: "\x1b3" }
  - { key: Key4, mods: Alt, chars: "\x1b4" }
  - { key: Key5, mods: Alt, chars: "\x1b5" }
  - { key: Key6, mods: Alt, chars: "\x1b6" }
  - { key: Key7, mods: Alt, chars: "\x1b7" }
  - { key: Key8, mods: Alt, chars: "\x1b8" }
  - { key: Key9, mods: Alt, chars: "\x1b9" }
  - { key: N, mods: Control, action: SpawnNewInstance }
window:
  decorations: none
  dynamic_title: true
  startup_mode: Maximized
