# .tmux.conf
#
# Configuration for tmux.

# Pane movements
bind-key j command-prompt -p "join pane from:" "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:" "join-pane -t '%%'"

# Powerline
source "/Users/matt.coleman/Library/Python/3.7/lib/python/site-packages/powerline/bindings/tmux/powerline.conf"
