#!/bin/bash

main() {

  local checksum=$HOME/checksum/checksum

  # write checksum
  dd if=/dev/urandom of=$checksum bs=1M count=10 2> /dev/null

  # do backup
  obnam backup

  # verify
  obnam verify `dirname $checksum`

}

main
