#!/bin/bash

PATCHES_DIR=$HOME/tmp/patches

# update branch and master and generate a full-index diff
gen_patch() {

  set -e

  local repo=$(basename `git rev-parse --show-toplevel`)
  local lbranch=`git branch | grep '*' | awk '{print $2}'`

  for i in master $lbranch; do
    git checkout $i && git pull --rebase origin master
  done

  git diff --full-index master..$lbranch > \
    "${PATCHES_DIR}/${repo}_${lbranch}.patch"

  set +e

}
