#!/bin/bash
#
# Helper utilities for the priv store.

declare -A PRIV_MOUNTS
PRIV_MOUNTS[axios]="${HOME}/mnt/axios"
PRIV_MOUNTS[deontos]="${HOME}/mnt/deontos"
PRIV_MOUNTS[eidos]="${HOME}/mnt/eidos"
PRIV_MOUNTS[heiros]="${HOME}/mnt/heiros"
PRIV_MOUNTS[pragmata]="${HOME}/mnt/pragmata/priv"

# Figure out a current available priv mount
priv() {
  local desired_mount=
  local found_mount=

  if (($# > 0)); then
    desired_mount="${1}"
  fi

  if [[ -n "${desired_mount}" ]]; then
    # We supplied a priv mount to use
    found_mount="${PRIV_MOUNTS[$desired_mount]}"
  else
    # We should find a priv mount
    for mount in "${!PRIV_MOUNTS[@]}"; do
      if [[ -d "${PRIV_MOUNTS[$mount]}/pass" ]]; then
        found_mount="${PRIV_MOUNTS[$mount]}"
        break
      fi
    done
  fi

  export PRIV="${found_mount}"
  export GNUPGHOME="${PRIV}/gnupg"
  export PASSWORD_STORE_DIR="${PRIV}/pass"
}

# Initial invocation
priv
