#!/bin/bash

# figure out PRIV
priv() {
  for mount in deontos eidos; do
    if mountpoint "$HOME/mnt/$mount" &> /dev/null; then
      echo "$HOME/mnt/$mount"
      break
    fi
  done
}

export PRIV=`priv`
export PASSWORD_STORE_DIR=$PRIV/.pass
alias mutt='mutt -F $PRIV/.muttrc'
alias gpg='gpg --homedir $PRIV/.gnupg'
