#!/bin/bash
#
# Helper utilities for the priv store.

# Refershes a priv store mount.
repriv() {
  local mount=$1

  sudo killall gpg-agent
  sudo umount --force "${HOME}/mnt/${mount}"
  mount $mount
}

# Figure out a current available priv store mount.
priv() {
  for mount in deontos eidos; do
    if mountpoint "${HOME}/mnt/${mount}" &> /dev/null; then
      echo "${HOME}/mnt/${mount}"
      break
    fi
  done
}

export PRIV=`priv`
export PASSWORD_STORE_DIR=$PRIV/.pass
alias mutt='mutt -F $PRIV/.muttrc'
alias gpg='gpg --homedir $PRIV/.gnupg'
