#!/bin/bash

alias pa='sudo puppet agent'
alias pt='pa -t'
alias pe='pa --enable'
alias pd='pa --disable'

# runs puppet with an optional environment
function pr() {
  local environment="production"
  [ -n "$1" ] && environment="$1"

  pt --environment="${environment}"
}

# freezes puppet into an optional environment
function pf() {
  local environment="production"
  [ -n "$1" ] && environment=$1 && shift

  local passargs=
  (( $# > 0 )) && passargs="$@"

  pe && \
  pt --environment=${environment} ${passargs}
  pd
}
