#!/bin/bash
#
# Helper utilities for Puppet.

alias pa='sudo puppet agent'
alias pd='pa --disable'
alias pe='pa --enable'
alias pt='pa --test'

# Runs Puppet with an optional environment.
function pr() {
  local environment="production"
  [ -n "$1" ] && environment="$1"

  pt --environment="${environment}"
}

# Freezes puppet into an optional environment.
function pf() {
  local environment="production"
  [ -n "$1" ] && environment=$1 && shift

  local passargs=
  (( $# > 0 )) && passargs="$@"

  pe && pt --environment=${environment} ${passargs}
  pd
}
