#!/bin/bash
#
# General utility functions.

# Open a TCP port on the default interface.
fwopen() {
  if (( $# < 1 )); then
    echo "Usage: fwopen <port>";
    return 1;
  fi

  sudo firewall-cmd --add-port="${1}/tcp"
  sudo firewall-cmd --list-ports | grep $1
}

# Find all files with names containing a string.
fn() {
  find . -name "*$1*"
}

# Pause for a keystroke.
pause() {
  if grep 'bash' <<< $(echo $SHELL); then
    read -p "Press enter to continue."
  else
    read \?"Press enter to continue."
  fi
}

# Find large files under a directory.
duf() {
  if (( $# < 1 )); then
    echo "Usage: duf <source>";
    return 1;
  fi

  find $1 -type f -exec du -h {} \; | sort -h -r | head -n 20
}

# JSON friendly cURL call.
jcurl() {
  curl --header "Accept: application/json" --silent $1 | json_pp
}
