#!/bin/bash

# add me as an administrator to wordpress
wp_addme() {
  echo "Enter password: "
  read -s PASSWORD
  wp user create $USER "$USER@local.host" \
    --role=administrator --user_pass=$PASSWORD
}

# reset wordpress hostname
wp_url() {
  [[ -z $1 ]] && return 1

  local sql=/tmp/wp.out.sql
  local old_url=`wp option get siteurl`
  local new_url=$1

  wp db export $sql && \
  sed -i "s,$old_url,$new_url,g" $sql && \
  wp db drop && \
  wp db create && \
  wp db import $sql
}
